<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function myTest($test)
    {
        dump($test);

        return $this->getEntityManager()->createQuery(
            'SELECT p FROM AppBundle:Category p WHERE p.id = '.$test['id']
        )
            ->getResult();
    }
}
