<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function checkAndDeleteProductFromCarts($product)
    {
        return $this->getEntityManager()->createQuery(
            //"DELETE from 'cart_products' WHERE product_id = ". $product->getId()
            "DELETE from AppBundle:Products:usersCartOwners  WHERE product_id = ". $product->getId()
        )
            ->getResult();
    }
}
